name: Publish to Nextcloud app store

on:
  workflow_dispatch:
    inputs:
      appid:
        description: 'Application ID'
        required: true
      version:
        description: 'Version'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_URL: https://github.com/nextcloud/${{ github.event.inputs.appid }}/releases/download/v${{ github.event.inputs.version }}/${{ github.event.inputs.appid }}.tar.gz

    steps:
    - name: Download release package
      run: curl -f --output app.tar.gz -L $RELEASE_URL
    - name: Prepare signature data
      env:
        NEXTCLOUD_APPSTORE_SIGNING_PRIVATE_KEY: ${{secrets.NEXTCLOUD_APPSTORE_SIGNING_PRIVATE_KEY}}
      run: 'echo "$NEXTCLOUD_APPSTORE_SIGNING_PRIVATE_KEY" > app.key'
    - name: Sign release package
      run: |
        RELEASE_SIGNATURE="$(openssl dgst -sha512 -sign app.key app.tar.gz | openssl base64 -A)"
        echo "::set-env name=RELEASE_SIGNATURE::$RELEASE_SIGNATURE"
    - name: Publish release in app store
      env:
        NEXTCLOUD_APPSTORE_API_TOKEN: ${{secrets.NEXTCLOUD_APPSTORE_API_TOKEN}}
      run: 'curl -f -X POST https://apps.nextcloud.com/api/v1/apps/releases -H "Authorization: Token $NEXTCLOUD_APPSTORE_API_TOKEN" -H "Content-Type: application/json" -d ''{"download":"''$RELEASE_URL''", "signature": "''$RELEASE_SIGNATURE''"}'''
